workspace = { members = [ "lib/syrup","lib/syrup-derive", "lib/syrup-proc"] }
[package]
name = "rexa"
version = "0.1.0"
edition = "2021"
authors = ["Ash Walker <ash@ashwalker.net>"]

description = "An implementation of OCapN, a protocol for secure peer-to-peer networking."
readme = true
repository = "https://github.com/SignalWalker/rexa"
license = "LGPL-3.0-or-later"

categories = [ "asynchronous", "authentication", "concurrency", "cryptography", "network-programming" ]
keywords = [ "ocap", "ocapn", "object-capabilities" ]

[dependencies]
# meta
thiserror = "^1.0"
tracing = "^0.1"

# captp

# locators
# url = "^2.4"

# syrup
syrup = { path = "lib/syrup" }

# netlayers
futures = "^0.3"
## tor
arti-client = { version = "^0.12", git = "https://gitlab.torproject.org/tpo/core/arti", features = ["onion-service-client"], optional = true }
tor-rtcompat = { version = "^0.9", git = "https://gitlab.torproject.org/tpo/core/arti", features = [], optional = true }

[dev-dependencies]
proptest = { version = "^1.4" }
lazy_static = { version = "^1.4" }

[build-dependencies]

[features]
default = ["netlayer-onion"]
netlayer-onion = ["dep:arti-client", "dep:tor-rtcompat"]
