[package]
name = "rexa"
version = "0.1.0"
edition = "2021"
authors = ["Ash Walker <ash@ashwalker.net>"]

description = "An implementation of OCapN, a protocol for secure peer-to-peer networking."
readme = true
repository = "https://github.com/SignalWalker/rexa"
license = "LGPL-3.0-or-later"

categories = [
  "asynchronous",
  "authentication",
  "concurrency",
  "cryptography",
  "network-programming",
]
keywords = ["ocap", "ocapn", "object-capabilities"]

[dependencies]
# meta
thiserror = "^1.0"
tracing = "^0.1"

crossbeam = { version = "^0.8" }

# captp
dashmap = { version = "^5" }
## crypto
rand = { version = "^0.8", features = [] }
ed25519-dalek = { version = "^2", features = ["rand_core"] }

# locators
# url = "^2.4"

# syrup
syrup = { path = "lib/syrup" }

# netlayers
flume = { version = "^0.11", features = ["async"] }
futures = { version = "^0.3" }
smol = { version = "^2", optional = true }
tokio = { version = "^1.36", optional = true, features = ["io-util", "sync"] }
## tor
arti-client = { version = "^0.12", git = "https://gitlab.torproject.org/tpo/core/arti", features = [
  "onion-service-client",
], optional = true }
tor-rtcompat = { version = "^0.9", git = "https://gitlab.torproject.org/tpo/core/arti", features = [
], optional = true }

[dev-dependencies]
proptest = { version = "^1.4" }
lazy_static = { version = "^1.4" }

easy-parallel = "^3"
tracing-subscriber = { version = "^0.3", features = [
  "time",
  "env-filter",
  "parking_lot",
  "local-time",
  "json",
] }
time = { version = "^0.3", features = ["formatting", "local-offset", "macros"] }

[build-dependencies]

[features]
default = ["futures", "extra_diagnostics"]
extra_diagnostics = []
futures = []
tokio = ["dep:tokio"]
netlayer-onion = ["dep:arti-client", "dep:tor-rtcompat"]
netlayer-mock = []
netlayer-tcpip-smol = ["dep:smol"]
