[licenses]
version = 2
allow = [
  "MIT",
  "MIT-0",
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "LGPL-3.0",
  "BSD-3-Clause",
]
confidence-threshold = 0.8
exceptions = [{ allow = ["Unicode-DFS-2016"], crate = "unicode-ident" }]

[licenses.private]
ignore = true
registries = ["sparse+https://git.ashwalker.net/api/packages/ash/cargo"]
